name: Process Last 10 Tags

on:
  workflow_dispatch:

jobs:
  find-tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.get_tags.outputs.tags }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Fetch last 10 tags
        id: get_tags
        run: |
          git fetch --prune --unshallow --tags || true
          # Grab last 10 tags like v01, v02, etc., sorted by creation date
          TAGS=$(git tag -l 'v[0-9][0-9]' --sort=-creatordate | head -n 2)
          # Turn them into a JSON array for the matrix
          JSON_TAGS=$(echo "${TAGS}" | jq -R -s 'split("\n") - [""]')
          echo "::set-output name=tags::${JSON_TAGS}"

  process-tags:
    needs: find-tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.find-tags.outputs.tags) }}
    steps:
      - name: Check out this specific tag
        uses: actions/checkout@v3
        with:
          ref: ${{ matrix.tag }}

      - name: Install CLI
        run: npm install -g add-gl-quotes-to-tsv-files

      - name: Process TSV files
        run: add-gl-quotes-to-tsv-files --ref ${{ matrix.tag }}

      - name: Attach zip file to release
        uses: akkuman/gitea-release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "*${{ matrix.tag }}_with_gl_quotes.zip"